name: Python Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production pages deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: make ci-bootstrap

    - name: Build
      run: make ci-build

    - name: Unit Test and Coverage
      run: make ci-test

  acceptance-test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: make ci-bootstrap  

    - name: Run acceptance tests
      run: make ci-test-acceptance 

    - name: Prepare results
      if: always()
      run: make prepare-results

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v3
    - name: Upload pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./test_results
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v2